<style lang="scss" scoped>
.legal {
  font-family: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;

  ul:nth-of-type(1) {
    list-style-type: upper-alpha;
  }
}
</style>

<template>
  <div class="legal">
    <p>La Política de Privacidad de www.raffles.com.ar es aplicable a todos los Usuarios del sitio web desde el momento de la aceptación de los Términos y Condiciones de Uso, y tiene como objetivo que los Usuarios conozcan el trato que RAFFLES les dará a sus datos personales.</p>
    <ol>
      <li><strong>Disposiciones Generales.</strong> La información personal de los Usuarios es de extrema importancia para RAFFLES. Es por ello que se utilizan todos los medios administrativos y técnicos a nuestro alcance así como todos los resguardos legales necesarios para asegurar la protección de los datos personales y la privacidad.<br>La presente Política de Privacidad se aplica a toda información personal de los Usuarios obtenidas como consecuencia de la utilización del sitio web y de la utilización de los diferentes servicios ofrecidos por RAFFLES.</li>
      <li><strong>Formas de obtención de datos.</strong> RAFFLES recogerá datos personales de los Usuarios a través de formularios e interacciones dentro del sitio web, de los contratos que realice y de las comunicaciones electrónicas con los Usuarios.</li>
      <li><strong>Finalidad.</strong> En cumplimiento de lo establecido en los arts. 2, 7 y 8 de la Ley 25.326 de Protección de Datos Personales de Argentina, RAFFLES no solicitará información que sea incompatible con la finalidad del sitio o de sus servicios, ni que directa o indirectamente revele datos sensibles de los Usuarios, como ser datos que revelan origen racial y étnico, opiniones políticas, convicciones religiosas, filosóficas o morales, afiliación sindical, información referente a la salud o a la vida sexual. De la misma manera RAFFLES solicita a los Usuarios no incluir esta información en el sitio web.</li>
      <li><strong>Datos recolectados.</strong> Los datos personales que RAFFLES recolecta a través del sitio web son: nombre y apellido, correo electrónico, servicios a contratar, descripción del proyecto deseado y presupuesto aproximado con el que cuenta el Usuario. A su vez el Usuario tendrá la opción de optar por recibir correos electrónicos con novedades.<br>Además de la información de contacto que el Usuario envíe a través del sitio web, RAFFLES también podrá recopilar y almacenar la información del Usuario mientras utilice el sitio web o contrate sus servicios.</li>
      <li><strong>Confidencialidad.</strong> La información personal es totalmente confidencial y RAFFLES tomará las medidas de seguridad para evitar su uso desautorizado de conformidad con lo dispuesto en la Ley 25.326 de Protección de Datos Personales de Argentina, y en concordancia con los estándares normativos de privacidad de la Unión Europea y Latinoamérica.<br>Las comunicaciones privadas que pudieran darse entre el personal de RAFFLES y los Usuarios o visitantes también serán consideradas como confidenciales. El acceso a toda esta información estará restringido mediante herramientas tecnológicas y estrictos controles internos.<br>Sin embargo no se considerarán confidenciales las comunicaciones electrónicas entre los Usuarios o entre estos y RAFFLES con sugerencias y/o consultas y/o en cumplimiento de condiciones de promociones o concursos, newsletters, publicidad o información solicitada. En estos casos RAFFLES podrá retener y utilizar libremente dichas comunicaciones.</li>
      <li><strong>Administración de la información.</strong> RAFFLES utilizará la información para los siguientes fines:
        <ol>
          <li>identificación y autenticación</li>
          <li>administración y gestión comercial</li>
          <li>mejora del servicio</li>
          <li>fines estadísticos</li>
          <li>envío de notificaciones, promociones o publicidad y actividades similares</li>
        </ol>
      <br>Los datos personales no serán difundidos ni empleados para un fin distinto o incompatible al tenido en cuenta al ser ingresados en la base.<br>RAFFLES podrá emplear a otras compañías y/o personas físicas para llevar a cabo tareas o funciones en su nombre. Entre los ejemplos de ese tipo podemos mencionar el de enviar correo postal y electrónico, retirar información reiterativa de las listas de usuarios, analizar datos en forma estadística, etc. Dichas personas cuentan con acceso a la información personal necesaria para cumplir con sus tareas y funciones, pero no pueden utilizarla con otros fines distintos.<br>Si se tratase de una comunicación de publicidad directa no requerida o consentida previamente por el Usuario, RAFFLES le otorgará al Usuario la posibilidad de ser retirado o bloqueado de dicha base de datos específica.<br>En caso de cesión o utilización para un fin diferente, RAFFLES solicitará a los Usuarios su consentimiento libre, expreso e informado. En el caso de venta, cesión, fusión, consolidación, venta de la totalidad o parte sustancial de sus activos, RAFFLES podrá revelar o transmitir dicha información a terceros.</li>
      <li><strong>Registro de la Base de Datos.</strong> Los datos recabados por el sitio web son incorporados a una base de datos de la cual Provincia Seguros S.A. es responsable. La misma se encuentra registrada en la Dirección Nacional de Protección de Datos Personales del Ministerio de Justicia y Derechos Humanos de la Nación (República Argentina) bajo el número de registro N° ____________, en cumplimiento de lo dispuesto en el art. 3 de la Ley 25.326.<br>La Dirección Nacional de Protección de Datos Personales, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales. El sitio web para consultas sobre responsables inscriptos es www.jus.gob.ar/datospersonales</li>
      <li><strong>>Derechos.</strong> El Usuario tiene la facultad de ejercer el derecho de acceso a sus datos en forma gratuita a intervalos no inferiores a seis (6) meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326. La Dirección Nacional de Protección de Datos Personales, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales.<br>Asimismo, se deja constancia que el titular de los datos podrá en cualquier momento solicitar el retiro o bloqueo de su nombre de los bancos de datos (Ley 25.326, art. 27, inc. 3). Esto se hace en cumplimiento de lo establecido en el Decreto 1558/2001, art. 27, párrafo 3, que establece que “en toda comunicación con fines de publicidad que se realice por correo, teléfono, correo electrónico, Internet u otro medio a distancia a conocer, se deberá indicar, en forma expresa y destacada, la posibilidad del titular del dato de solicitar el retiro o bloqueo, total o parcial, de su nombre de la base de datos. A pedido del interesado, se deberá informar el nombre del responsable o usuario del banco de datos que proveyó la información”.</li>
      <li><strong>Procedimiento.</strong> Para que el Usuario pueda hacer efectivo su derecho de acceso, rectificación, actualización, supresión y confidencialidad de datos, deberá tener en consideración lo siguiente:
        <ol>
          <li>La solicitud de obtención de información, rectificación, actualización o supresión de datos personales debe efectuarse por carta documento dirigida a RAFFLES ARGENTINA SRL - CUIT 30-71470679-5, Julián S. Agüero 1511, Florida Oeste, Provincia de Buenos Aires, acreditando la identidad y el legítimo derecho.</li>
          <li>Una vez recepcionada y aprobada dicha solicitud, RAFFLES la contestará en lenguaje accesible y entendible, previa confirmación de identidad, dentro de los diez (10) días corridos para el caso de pedido de información mientras que para el pedido de rectificación, actualización o supresión de datos, el responsable contará con cinco (5) días hábiles para contestar.</li>
          <li>RAFFLES informará de la forma más concreta y claramente posible y contestará de acuerdo a la preferencia que expresamente haya manifestado el interesado en su solicitud. En ningún caso el informe podrá revelar datos pertenecientes a terceros.</li>
          <li>La información podrá ser denegada cuando de tal modo se pudieran obstaculizar actuaciones judiciales o administrativas en curso.</li>
        </ol>
      </li>
      <li><strong>Seguridad de la información.</strong> RAFFLES se ocupa por mantener todo el tiempo la seguridad de la información personal que brindan los Usuarios, implementando las medidas técnicas y organizativas internas necesarias para garantizar la seguridad y confidencialidad de los datos y tratando por todos los medios de evitar el acceso no autorizado a los mismos. Sin embargo, en razón del estado actual de la tecnología, RAFFLES no puede garantizar que el acceso no autorizado no ocurrirá nunca.</li>
      <li><strong>Uso de cookies.</strong> Los Usuarios conocen y aceptan de plena conformidad que RAFFLES podrá utilizar un sistema de seguimiento mediante el uso de cookies. Las cookies son archivos que se alojan en el disco rígido, con una duración limitada en el tiempo que ayudan a personalizar los servicios. Las mismas permitirán recoger datos a efectos de la autenticación de Usuarios, validación de identidad y para evaluar el comportamiento y la demografía de los Usuarios con el fin de ofrecerles un mejor servicio.<br>Asimismo, podrán utilizarse con fines estadísticos tales como: fecha de la primera visita, número de veces que se ha visitado, fecha de la última visita, URL y dominio de la que proviene, explorador utilizado, resolución de la pantalla, entre otras acciones del Usuario. También son utilizadas las cookies para promover y hacer cumplir las reglas y seguridad del sitio. Toda esta información no será asociada a los datos personales de los Usuarios.<br>No obstante, el Usuario puede desactivar y/o eliminar estas cookies a través de su navegador de Internet, sabiendo que con esta opción, es posible que no se puedan acceder a ciertos contenidos del Sitio.<br>No obstante, el Usuario puede desactivar y/o eliminar estas cookies a través de su navegador de Internet, sabiendo que con esta opción, es posible que no se puedan acceder a ciertos contenidos del Sitio.<br>RAFFLES pone en su conocimiento que en ocasiones, puede haber existencia de cookies o archivos de similares características instalados por terceros en algunos enlaces con el sitio web que no son controlados por RAFFLES. RAFFLES es responsable solamente por la utilización de cookies por su propio sitio web y no por el uso de cookies por parte de anunciantes.</li>
      <li><strong>Enlaces con otros sitios web.</strong> El sitio web puede contener enlaces o links publicitarios con sitios de terceros. Sin embargo RAFFLES no dispone de control alguno ni ostenta responsabilidad alguna sobre las políticas o medidas de protección de datos de otros sitios web.</li>
    </ol>
    <i>La presente Política de Privacidad forma parte integrante de los Términos y Condiciones de Uso del sitio web.<br>Última modificación 1 de junio de 2015.</i>
  </div>
</template>

<script>
export default {
    name: "PolicyOfPrivacy"
}
</script>
