<style lang="scss" scoped>
.legal {
  font-family: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;

  ul:nth-child(1) {
    list-style-type: upper-alpha;
  }
}
</style>

<template>
  <div class="legal">
    <ol>
      <li><strong>Aceptación del Contrato.</strong> Los presentes Términos y Condiciones regulan la navegación y correcta utilización del sitio www.raffles.com.ar (en adelante, el “sitio web”) por parte de cualquier persona que acceda al mismo. El acceso y/o uso del sitio web es totalmente voluntario y atribuye a quien lo realiza la condición de USUARIO.<br> Estos Términos y Condiciones son de carácter obligatorio y vinculante para el USUARIO, y constituyen un contrato entre éste y los responsables de RAFFLES ARGENTINA SRL - CUIT 30-71470679-5, Julián Segundo Agüero 1511, 5º B, Florida Oeste (CP 1604), Provincia de Buenos Aires, (en adelante “RAFFLES”). Sin embargo, no podrá ser interpretado como un contrato de licencia, sociedad, mandato, agencia, ni de cualquier otro tipo.<br> Por lo tanto, la aceptación de los presentes Términos y Condiciones implica que el USUARIO los leyó y los comprendió. Si el USUARIO no estuviera de acuerdo con estas disposiciones, deberá abstenerse de acceder al sitio web y/o de utilizar cualquiera de sus servicios.</li>
      <li><strong>Modificación del Contrato.</strong> Estos Términos y Condiciones podrán ser modificados o sustituidos en cualquier momento y a exclusivo criterio de RAFFLES. Las modificaciones entrarán en vigencia desde su publicación en el sitio web. La utilización que el USUARIO haga con posterioridad a dicha publicación constituirá la aceptación a la misma. Si el USUARIO no estuviere de acuerdo con las modificaciones de los Términos y Condiciones podrá prescindir de utilizar los servicios de RAFFLES y/o darse de baja como USUARIO del sitio web.</li>
      <li><strong>Objetivo.</strong> RAFFLES es una empresa joven de desarrollos informáticos que busca conectar a la gente con la tecnología de manera accesible y creativa. El objetivo de RAFFLES es el de solucionar problemas tanto para el usuario final como para emprendedores y empresas, a través de productos tales como plataformas transaccionales, sitios web y aplicaciones móviles.<br> RAFFLES es una empresa pionera en detectar y resolver problemas emergentes de nuestra sociedad, y en constante actualización.</li>
      <li><strong>Navegación.</strong> El USUARIO puede navegar libremente por el sitio web, sin embargo para contratar los servicios de RAFFLES deberá ser mayor de edad, estar legalmente capacitado y aceptar estos Términos y Condiciones.<br> RAFFLES no se responsabiliza por la veracidad o certeza de los datos provistos por el USUARIO y podrá sancionar o dar de baja a USUARIOS en la medida que considere que están violando este contrato o las leyes vigentes.</li>
      <li><strong>Servicios.</strong>Los USUARIOS podrán acceder y contratar los siguientes servicios:
        <ol>
          <li>Desarrollo Web</li>
          <li>Consultoría</li>
        </ol>
      </li>
      <li><strong>Obligaciones generales.</strong> Los USUARIOS se obligan a utilizar el sitio web en forma responsable. En particular, y sin que la lista que figura a continuación implique excluir otros actos, el USUARIO se obliga a:
        <ul>
          <li>utilizar el sitio web de manera diligente, correcta y lícita.</li>
          <li>abstenerse de copiar, modificar, alterar y/o manipular el software y/o utilizar ingeniería inversa.</li>
          <li>completar formularios con datos válidos y verdaderos.</li>
          <li>abstenerse de subir al sitio web cualquier contenido en forma o con fines contrarios a la ley, la moral, a las buenas costumbres y/o al orden público.</li>
          <li>abstenerse de asumir la identidad idéntica o similar de otra persona o empresa.</li>
          <li>respetar todos y cada uno de los derechos que surgen de la titularidad del sitio web y sus contenidos,
          de conformidad con lo dispuesto en los Términos y Condiciones.</li>
          <li>proporcionar una dirección de correo electrónico que sea del propio USUARIO.</li>
          <li>abstenerse de efectuar acciones indebidas sobre el sitio web o subir malware, virus o contenido dañino o peligroso, o acciones que generen una carga desproporcionada sobre la infraestructura del sitio o demandas de tráfico excesivo, que perjudiquen de alguna forma su contenido e infraestructura, el contenido de otros usuarios, etc.</li>
        </ul>
      </li>
      <li><strong>Sanciones.</strong> A los efectos de hacer cumplir los presentes Términos y Condiciones, RAFFLES estará facultada a aplicar las siguientes sanciones a los USUARIOS, a saber: a) apercibimiento, b) suspensión de uso del perfil, c) retiro parcial o total de contenidos y d) eliminación de la cuenta de USUARIO e inhabilitación para poder ingresar al sitio.<br> Las mismas podrán ser de manera temporal o definitiva, de manera separada o conjunta, a exclusivo criterio de RAFFLES. Asimismo, en caso de detectarse actividades fraudulentas y/o ilegales, RAFFLES se encontrará facultada a realizar las denuncias formales en los fueros judiciales correspondientes.</li>
      <li><strong>Responsabilidades.</strong> Se deja expresa constancia que RAFFLES no puede garantizar ni controlar en su totalidad la capacidad legal para contratar de los USUARIOS y no se responsabiliza por las decisiones tomadas a partir de la información o contenidos suministrados en el sitio web, ni por los daños y perjuicios que puedan producirse a USUARIOS o terceros con motivo de decisiones que tengan como fundamento la información o los datos brindados en el sitio web.<br> RAFFLES no está obligada a investigar o hacer frente a cualquier queja o aviso sobre el incumplimiento de estos Términos y Condiciones por parte de uno o más USUARIOS. Tampoco está obligada a tomar alguna medida o realizar alguna acción a favor o en contra de uno o más USUARIOS.<br> Si bien RAFFLES hará su mayor esfuerzo para cumplir con las expectativas de los USUARIOS, no estará obligada a responder o actuar ante pedidos, reclamos o mensajes enviados.<br> Si bien RAFFLES hará su mayor esfuerzo para cumplir con las expectativas de los USUARIOS, no estará obligada a responder o actuar ante pedidos, reclamos o mensajes enviados.<br> El USUARIO entiende y acepta que cualquier falta de acción por parte de los responsables de RAFFLES ante un incumplimiento o violación de alguna disposición de los Términos y Condiciones no implica conformidad con tal actitud.</li>
      <li><strong>Responsabilidades.</strong> Se deja expresa constancia que RAFFLES no puede garantizar ni controlar en su totalidad la capacidad legal para contratar de los USUARIOS y no se responsabiliza por las decisiones tomadas a partir de la información o contenidos suministrados en el sitio web, ni por los daños y perjuicios que puedan producirse a USUARIOS o terceros con motivo de decisiones que tengan como fundamento la información o los datos brindados en el sitio web.<br> RAFFLES no está obligada a investigar o hacer frente a cualquier queja o aviso sobre el incumplimiento de estos Términos y Condiciones por parte de uno o más USUARIOS. Tampoco está obligada a tomar alguna medida o realizar alguna acción a favor o en contra de uno o más USUARIOS.<br> Si bien RAFFLES hará su mayor esfuerzo para cumplir con las expectativas de los USUARIOS, no estará obligada a responder o actuar ante pedidos, reclamos o mensajes enviados.<br> El USUARIO entiende y acepta que cualquier falta de acción por parte de los responsables de RAFFLES ante un incumplimiento o violación de alguna disposición de los Términos y Condiciones no implica conformidad con tal actitud.</li>
      <li><strong>Indemnidad.</strong> En caso que las acciones de un USUARIO generen algún tipo de reclamo o acción extrajudicial, administrativa y/o judicial contra RAFFLES, el USUARIO infractor se compromete a mantener indemne a RAFFLES, sus socios, representantes y/o empleados.</li>
      <li>Privacidad de la información personal. La protección de los datos personales de los USUARIOS y el cumplimiento de la legislación vigente en la materia es fundamental para RAFFLES, que utiliza todos los medios técnicos y de seguridad posible así como los legales para el resguardo de la información personal de los USUARIOS.<br> Para mayor información lea atentamente las Políticas de Privacidad, que forman parte integrante de los presentes Términos y Condiciones.</li>
      <li><strong>Propiedad intelectual.</strong> El sitio web y todos sus contenidos, incluyendo el diseño de la página, dominios, redes sociales, perfiles y canales oficiales, las marcas, nombres comerciales, textos, gráficos, templates, logos, imágenes, íconos, software, productos y servicios, así como también los derechos de autor y copyright por todos los contenidos del sitio web están protegidos por la legislación vigente en materia de propiedad intelectual e industrial siendo directa o indirectamente propiedad de RAFFLES o de los licenciatarios autorizados por cesión expresa de sus titulares.<br> Por este motivo, no podrán ser objeto de explotación, copia, distribución, reproducción, modificación, transformación, cesión o comunicación pública, salvo autorización previa y expresa de RAFFLES y/o de los titulares de dichos derechos.<br> Se advierte al USUARIO que el uso no autorizado del material antes mencionado, o para finalidades ilegales o contrarias a la moral y las buenas costumbres, supone una violación a la ley y los responsables de RAFFLES se reservan el derecho de ejercer las acciones administrativas y/o judiciales que por derecho correspondan, sean tanto de derecho privado como penales, contra quienes infrinjan o violen los derechos amparados por este punto y cualquier otro de los Términos y Condiciones.<br> Si el USUARIO considera que en el sitio web se atenta de algún modo contra derechos de propiedad intelectual de terceros, deberá notificarlo mediante correo electrónico, junto con la información y documentación que respalde la mencionada consideración. En esta dirección de correo electrónico solo se tratarán los mensajes sobre violación a derechos de propiedad intelectual. En caso que RAFFLES compruebe dicha situación, la información en conflicto será sometida a análisis para su eventual remoción.<br> Los USUARIOS reconocen el derecho de RAFFLES de utilizar libremente los contenidos que los USUARIOS hayan ingresado al sitio web o enviado por correo electrónico, para fines publicitarios, de promoción, e-mail marketing y/o estadísticos.</li>
      <li><strong>Avisos publicitarios y links.</strong> El sitio web eventualmente podrá contar con avisos publicitarios, enlaces y links de terceros. Cuando el USUARIO acceda a los mismos e ingrese en otros sitios que no pertenezcan a los responsables de RAFFLES estará sujeto a los términos y condiciones de dichos sitios y el USUARIO deberá leer detenidamente sus políticas de acceso y uso.<br> RAFFLES no ejerce ningún tipo de control sobre esos sitios ni sus contenidos y, por lo tanto, no asume responsabilidad alguna ni garantiza la legalidad, actualidad, calidad ni utilidad de los contenidos, operaciones e informaciones que se comuniquen, reproduzcan y/o realicen en sitios enlazados de terceros ni la ausencia de nocividad de tales contenidos, por lo que el USUARIO exime de toda responsabilidad a RAFFLES por los contenidos incluidos en los referidos sitios o los servicios que en ellos se brindan o promocionan.<br> La presencia de publicidades, enlaces o links en el sitio web tienen una finalidad meramente informativa y en ningún caso suponen sugerencia, invitación o recomendación sobre los mismos.</li>
      <li><strong>Medidas de Seguridad.</strong> RAFFLES implementa por sí o a través de terceros medidas de seguridad para el sitio web que protejan su propia información y la de sus USUARIOS. Sin embargo, RAFFLES no garantiza fehacientemente que el sitio web se encuentre libre de errores, virus, troyanos, gusanos o cualquier otro malware informático que pueda llegar a destruir, dañar o alterar el normal funcionamiento de una computadora, dispositivo o sistema, propio o ajeno, o tomar control indebido de los mismos.<br> Por lo tanto, es responsabilidad y obligación exclusiva del USUARIO contar con las herramientas informáticas adecuadas para detectar, eliminar y desinfectar malware, limpiar y/o prevenir cualquier tipo de elementos y/o posibles daños de esta naturaleza.<br> RAFFLES no se responsabiliza por cualquier daño que pueda producirse en los equipos, dispositivos o sistemas informáticos del USUARIO o de terceros como consecuencia de la navegación o utilización del sitio web y/o su plataforma, ni está obligada a reparar errores, ni hacerse cargo de las pérdidas, costos o gastos que se derive de estos hechos. Es responsabilidad de los USUARIOS mantener bajo resguardo las claves de acceso al sitio y demás sistemas instalados en su cuenta.</li>
      <li><strong>Interrupción del Sitio.</strong> RAFFLES se reserva el derecho de interrumpir, suspender o modificar en cualquier momento los contenidos ofrecidos, ya sea en forma permanente o transitoria. No se requerirá la conformidad del USUARIO, ni será necesario aviso previo alguno. Tampoco se garantiza el acceso o posibilidad de uso permanente del sitio web, ya que éste podría interrumpirse por mantenimiento o por cuestiones técnicas ajenas a RAFFLES. RAFFLES no se responsabiliza por los daños y perjuicios de cualquier tipo que pueda experimentar el USUARIO que tengan como causa fallas o falta de correcta conexión en las redes de telecomunicaciones y que provoquen la interrupción o cancelación de la información y contenidos brindados en RAFFLES, ya sea durante la navegación en el mismo o con carácter previo.</li>
      <li><strong>Jurisdicción y ley aplicable.</strong> Los presentes Términos y Condiciones se encuentran regidos sin excepción y en todos sus puntos por las leyes de la República Argentina y serán interpretados de acuerdo a ellas.<br> Ante cualquier diferencia, desacuerdo o conflicto derivado de la interpretación, validez, alcance y/o aplicación de los presentes Términos y Condiciones, el USUARIO se comunicará con los responsables de RAFFLES de manera fehaciente, haciéndole llegar su reclamo, para que las partes traten de arribar a un acuerdo en el plazo de treinta días corridos desde la notificación de la controversia. En caso de que no sea posible arribar a una solución amigable, en el plazo mencionado, las partes se someterán a los Tribunales ordinarios de la Ciudad Autónoma de Buenos Aires, República Argentina, con competencia en la materia.</li>
    </ol>
    <i>RAFFLES ARGENTINA SRL - CUIT 30-71470679-5, Julián Segundo Agüero 1511, 5º B, Florida Oeste, Provincia de Buenos Aires. Última modificación: 1 de junio de 2015.</i>
  </div>
</template>

<script>
export default {
    name: "TermsAndConditions"
}
</script>
